In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

boston = pd.read_csv('boston.csv')

features = boston.drop(columns = 'PRICE')
target = boston['PRICE']

scaler = StandardScaler()
features_scaled = scaler.fit_transform(features)

In [4]:
from sklearn.linear_model import Lasso

lasso = Lasso(alpha=0.5)
lasso.fit(features_scaled, target)

Lasso(alpha=0.5)

In [5]:
lasso.intercept_

np.float64(22.532806324110677)

In [7]:
lasso.coef_

array([-0.11526463,  0.        , -0.        ,  0.39707879, -0.        ,
        2.97425861, -0.        , -0.17056942, -0.        , -0.        ,
       -1.59844856,  0.54313871, -3.66614361])

In [9]:
lasso_10 = Lasso(alpha=10)
lasso_10.fit(features_scaled, target)

lasso_10.coef_

array([-0.,  0., -0.,  0., -0.,  0., -0.,  0., -0., -0., -0.,  0., -0.])

In [10]:
from sklearn.linear_model import LassoCV

lasso_cv = LassoCV(alphas=[0.1, 1.0, 10.0])
lasso_cv.fit(features_scaled, target)

LassoCV(alphas=[0.1, 1.0, 10.0])

In [11]:
lasso_cv.intercept_

np.float64(22.532806324110677)

In [12]:
lasso_cv.coef_

array([-0.63230364,  0.70840931, -0.        ,  0.65760723, -1.57419335,
        2.82626903, -0.        , -2.42207901,  1.19593681, -0.84646778,
       -1.92249345,  0.76216539, -3.72618383])

In [13]:
lasso_cv.alpha_

np.float64(0.1)

In [15]:
lasso_cv_n = LassoCV(n_alphas=1000, cv=5)
lasso_cv_n.fit(features_scaled, target)

lasso_cv_n.alpha_

/home/jeongjun/anaconda3/envs/jeongjun/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:1622: FutureWarning: 'n_alphas' was deprecated in 1.7 and will be removed in 1.9. 'alphas' now accepts an integer value which removes the need to pass 'n_alphas'. The default value of 'alphas' will change from None to 100 in 1.9. Pass an explicit value to 'alphas' and leave 'n_alphas' to its default value to silence this warning.
  warnings.warn(


np.float64(0.15326173083090822)

In [19]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

boston = pd.read_csv('boston.csv')

features = boston.drop(columns='PRICE')
target = boston['PRICE']

scaler = StandardScaler()
features_scaled = scaler.fit_transform(features)

In [20]:
from sklearn.linear_model import ElasticNet

elastic = ElasticNet(alpha=0.5)
elastic.fit(features_scaled, target)

ElasticNet(alpha=0.5)

In [21]:
elastic.intercept_

np.float64(22.532806324110677)

In [23]:
elastic.coef_

array([-0.4018915 ,  0.2396599 , -0.2685624 ,  0.57510501, -0.49114456,
        2.72233629, -0.        , -0.71295364,  0.        , -0.23510262,
       -1.49012153,  0.60921792, -2.8297881 ])

In [24]:
lasso_10 = Lasso(alpha=10)
lasso_10.fit(features_scaled, target)

lasso_10.coef_

array([-0.,  0., -0.,  0., -0.,  0., -0.,  0., -0., -0., -0.,  0., -0.])

In [25]:
elastic_10 = ElasticNet(alpha=10)
elastic_10.fit(features_scaled, target)

elastic_10.coef_

array([-0.        ,  0.        , -0.        ,  0.        , -0.        ,
        0.2033143 , -0.        ,  0.        , -0.        , -0.        ,
       -0.        ,  0.        , -0.27547627])

In [26]:
from sklearn.linear_model import ElasticNetCV

elastic_cv = ElasticNetCV(alphas=[0.1, 1.0, 10.0])
elastic_cv.fit(features_scaled, target)

ElasticNetCV(alphas=[0.1, 1.0, 10.0])

In [27]:
elastic_cv.intercept_

np.float64(22.532806324110677)

In [28]:
elastic_cv.coef_

array([-6.81235427e-01,  7.06879030e-01, -1.86479568e-01,  7.01296329e-01,
       -1.39094132e+00,  2.82983389e+00, -5.51048932e-04, -2.25182349e+00,
        1.15285754e+00, -8.29052192e-01, -1.85449077e+00,  7.92187819e-01,
       -3.48912360e+00])

In [29]:
elastic_cv.alpha_

np.float64(0.1)

In [31]:
elastic_cv_n = ElasticNetCV(n_alphas=1000, cv = 5) # 내부적으로 α 값들을 로그 스케일로 1000개 생성하여 탐색
elastic_cv_n.fit(features_scaled, target)

elastic_cv_n.alpha_

/home/jeongjun/anaconda3/envs/jeongjun/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:1622: FutureWarning: 'n_alphas' was deprecated in 1.7 and will be removed in 1.9. 'alphas' now accepts an integer value which removes the need to pass 'n_alphas'. The default value of 'alphas' will change from None to 100 in 1.9. Pass an explicit value to 'alphas' and leave 'n_alphas' to its default value to silence this warning.
  warnings.warn(


np.float64(0.18631486463847485)

In [33]:
!pip install mglearn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 581.4/581.4 kB 11.5 MB/s  0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [mglearn]


In [35]:
# 필수 라이브러리
import numpy as np
import mglearn
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LassoCV, ElasticNetCV

# -----------------------------
# 1. 데이터 로드
# -----------------------------
X, y = mglearn.datasets.load_extended_boston()

# -----------------------------
# 2. 표준화 (필수)
# -----------------------------
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# -----------------------------
# 3. alpha 후보 설정
# -----------------------------
alphas = [0.001, 0.01, 0.1, 1, 10, 100, 1000]

# -----------------------------
# 4. Lasso 회귀 (CV)
# -----------------------------
lasso_cv = LassoCV(
    alphas=alphas,
    cv=5,
    max_iter=100000
)

lasso_cv.fit(X_scaled, y)

print("===== Lasso 결과 =====")
print("최적 alpha:", lasso_cv.alpha_)
print("절편 (intercept):", lasso_cv.intercept_)
print("회귀 계수 (coef):")
print(lasso_cv.coef_)
print()

# -----------------------------
# 5. ElasticNet 회귀 (CV)
# -----------------------------
elastic_cv = ElasticNetCV(
    alphas=alphas,
    l1_ratio=0.5,   # Lasso : Ridge = 50 : 50
    cv=5,
    max_iter=100000
)

elastic_cv.fit(X_scaled, y)

print("===== ElasticNet 결과 =====")
print("최적 alpha:", elastic_cv.alpha_)
print("절편 (intercept):", elastic_cv.intercept_)
print("회귀 계수 (coef):")
print(elastic_cv.coef_)


===== Lasso 결과 =====
최적 alpha: 0.1
절편 (intercept): 22.532806324110684
회귀 계수 (coef):
[-0.          0.          0.          0.         -0.          0.
  0.         -0.68366546  1.06339468  0.          0.          0.
 -0.          0.          0.         -0.          1.46166047 -0.9373223
 -0.         -0.         -0.         -0.         -0.         -0.
 -0.17564559 -0.          0.         -0.09882669  0.          0.
  0.01672564 -0.          0.          0.         -0.          0.11091395
  0.         -0.          0.22181722  0.         -0.         -0.
  0.         -0.25698252  0.          0.          0.          0.
 -0.          0.         -1.09654653 -0.          0.          0.
 -0.         -0.          0.          0.50479538  0.         -0.
 -1.13188241 -0.         -0.02227598 -0.         -0.         -0.
 -0.         -0.45543558  5.40004968 -0.         -0.         -0.
 -0.08989332 -1.6986119   0.29484706 -2.49179941  0.         -0.34638909
  0.          0.         -0.         -0.        